<?php

const CREATE_ACCOUNT_ONBOARDING_PERCENTAGE = 0;
const ACTIVATE_ACCOUNT_ONBOARDING_PERCENTAGE = 20;
const PROFILE_INFORMATION_ONBOARDING_PERCENTAGE = 40;
const JOBS_INTERESTED_ONBOARDING_PERCENTAGE = 50;
const EXPERINCE_ONBOARDING_PERCENTAGE = 70;
const FREELANCER_ONBOARDING_PERCENTAGE = 90;
const APPROVAL_WAITING_ONBOARDING_PERCENTAGE = 99;
const APPROVAL_ONBOARDING_PERCENTAGE = 100;